apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcommerce-config
  namespace: cloudcommerce
data:
  APP_ENV: "development"
  JWT_EXPIRY: "24h"
  REDIS_URL: "redis://redis:6379"
  NATS_URL: "nats://nats:4222"
  USER_SERVICE_URL: "http://user-service:8081"
  PRODUCT_SERVICE_URL: "http://product-service:8083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: cloudcommerce
data:
  init-databases.sql: |
    CREATE DATABASE identity_db;
    CREATE DATABASE tenant_db;
    CREATE DATABASE catalog_db;
    CREATE DATABASE inventory_db;
    CREATE DATABASE order_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE review_db;
