apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcommerce

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - api-gateway.yaml
  - user-service.yaml
  - product-service.yaml
  - storefront.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cloudcommerce
  app.kubernetes.io/managed-by: kustomize
