apiVersion: v1
kind: Namespace
metadata:
  name: cloudcommerce
  labels:
    app.kubernetes.io/part-of: cloudcommerce
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudcommerce-system
  labels:
    app.kubernetes.io/part-of: cloudcommerce
