apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloudcommerce
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: cloudcommerce/product-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: cloudcommerce-config
                  key: APP_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudcommerce-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: cloudcommerce-config
                  key: JWT_EXPIRY
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/catalog_db?sslmode=disable"
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudcommerce-config
                  key: REDIS_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: cloudcommerce
spec:
  selector:
    app: product-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service
  namespace: cloudcommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
